### ISSUE TITLE
Do UI work.

### ISSUE THREAD

**Issue by ateesdalejr** [ateesdalejr/autofollow#2]
@csf30816 Is assigned to do the UI work for the website.

**Comment by bob1171** [comment]
yes

**Comment by ateesdalejr** [comment]
@bob1171 Yes what?

**Comment by csf30816** [comment]
Don't worry I'm on it. I am aiming for simple but neat :)

**Comment by ateesdalejr** [comment]
@csf30816 Sounds good. 👍

**Comment by csf30816** [comment]
Thanks :)

**Comment by ateesdalejr** [comment]
This is completed! Closing.
