### ISSUE TITLE
Add advertisements to UI.

### ISSUE THREAD

**Issue by ateesdalejr** [ateesdalejr/autofollow#3]
Should we add a separate box to the UI or make the ads part of the background?

@csf30816 , we need to set up an <https://a-ads.com> account with a shared BTC withdrawal address. I'm guessing the way to do this is to share the private key with you should be simple enough.  I can just sweep the key in electron and email it to you. You can import it into your wallet to see the key's current balance and send and complete transactions with it easily enough.

**Comment by ateesdalejr** [comment]
@csf30816 I've emailed you the withdrawal address private key as well as the username and password to the a-ads account. 👍 It looks like we're good to go on spamming this across scratch.

**Comment by ateesdalejr** [comment]
If you've got any tips for how the ad can be improved in the UI please tell.

**Comment by csf30816** [comment]
Well, I have improved the ad's in the UI by making their width resposive :)

**Comment by csf30816** [comment]
Although we should create an A-ADS Unit that is square for some sort of corner ad :)

**Comment by ateesdalejr** [comment]
@csf30816 I think this is pretty good for now. So I'll close this issue.
